In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv("insurance_pre.csv")

dataset.shape
dataset.info()

dataset = pd.get_dummies(dataset, drop_first=True, dtype=int)

independent = dataset[
    ['age', 'bmi', 'children', 'sex_male', 'smoker_yes']
]

dependent = dataset[['charges']]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    independent,
    dependent,
    test_size=0.30,
    random_state=0
)

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 72.2 KB

In [2]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(random_state=0)

regressor.fit(X_train, y_train.values.ravel())

y_pred = regressor.predict(X_test)

from sklearn.metrics import r2_score

r_score = r2_score(y_test, y_pred)

print("R2 Score:", r_score)

R2 Score: 0.8539781318598829

In [3]:
criterion_values = ['squared_error', 'absolute_error']
max_features_values = [10, 100, 'sqrt', 'log2']
n_estimators_values = [10, 100]

results = []

for criterion in criterion_values:
    for max_features in max_features_values:
        for n_estimators in n_estimators_values:

            regressor = RandomForestRegressor(
                criterion=criterion,
                max_features=max_features,
                n_estimators=n_estimators,
                random_state=0
            )

            regressor.fit(X_train, y_train.values.ravel())

            y_pred = regressor.predict(X_test)

            r_score = r2_score(y_test, y_pred)

            results.append({
                'criterion': criterion,
                'max_features': max_features,
                'n_estimators': n_estimators,
                'R2': r_score
            })

results_df = pd.DataFrame(results)

results_df

         criterion max_features  n_estimators        R2
0    squared_error           10            10  0.833786
1    squared_error           10           100  0.853978
2    squared_error          100            10  0.833786
3    squared_error          100           100  0.853978
4    squared_error         sqrt            10  0.851654
5    squared_error         sqrt           100  0.871100
6    squared_error         log2            10  0.851654
7    squared_error         log2           100  0.871100
8   absolute_error           10            10  0.836387
9   absolute_error           10           100  0.849802
10  absolute_error          100            10  0.836387
11  absolute_error          100           100  0.849802
12  absolute_error         sqrt            10  0.857975
13  absolute_error         sqrt           100  0.869248
14  absolute_error         log2            10  0.857975
15  absolute_error         log2           100  0.869248

In [4]:
max_depth_values = [None, 3, 5, 8, 10, 15]

results = []

for max_depth in max_depth_values:

    regressor = RandomForestRegressor(
        criterion='squared_error',
        max_features='sqrt',
        n_estimators=100,
        max_depth=max_depth,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    results.append({
        'max_depth': max_depth,
        'R2': r_score
    })

results_df = pd.DataFrame(results).sort_values(
    by='R2', ascending=False
)

results_df

   max_depth        R2
3        8.0  0.885274
2        5.0  0.879747
4       10.0  0.877660
5       15.0  0.872752
0        NaN  0.871100
1        3.0  0.804200

In [5]:
min_samples_split_values = [2, 5, 10, 20]

results = []

for min_samples_split in min_samples_split_values:

    regressor = RandomForestRegressor(
        criterion='squared_error',
        max_features='sqrt',
        n_estimators=100,
        max_depth=8,
        min_samples_split=min_samples_split,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    results.append({
        'min_samples_split': min_samples_split,
        'R2': r_score
    })

results_df = pd.DataFrame(results).sort_values(
    by='R2', ascending=False
)

results_df

   min_samples_split        R2
0                  2  0.885274
2                 10  0.885173
1                  5  0.882142
3                 20  0.880429

In [6]:
min_samples_leaf_values = [1, 2, 5, 10]

results = []

for min_samples_leaf in min_samples_leaf_values:

    regressor = RandomForestRegressor(
        criterion='squared_error',
        max_features='sqrt',
        n_estimators=100,
        max_depth=8,
        min_samples_split=2,
        min_samples_leaf=min_samples_leaf,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    results.append({
        'min_samples_leaf': min_samples_leaf,
        'R2': r_score
    })

results_df = pd.DataFrame(results).sort_values(
    by='R2', ascending=False
)

results_df

   min_samples_leaf        R2
0                 1  0.885274
1                 2  0.883442
2                 5  0.878079
3                10  0.872061

In [7]:
max_leaf_nodes_values = [None, 5, 10, 20, 50]

results = []

for max_leaf_nodes in max_leaf_nodes_values:

    regressor = RandomForestRegressor(
        criterion='squared_error',
        max_features='sqrt',
        n_estimators=100,
        max_depth=8,
        min_samples_split=2,
        min_samples_leaf=1,
        max_leaf_nodes=max_leaf_nodes,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    results.append({
        'max_leaf_nodes': max_leaf_nodes,
        'R2': r_score
    })

results_df = pd.DataFrame(results).sort_values(
    by='R2', ascending=False
)

results_df

   max_leaf_nodes        R2
0             NaN  0.885274
4            50.0  0.883401
3            20.0  0.870480
2            10.0  0.846603
1             5.0  0.762254

In [8]:
min_impurity_decrease_values = [0, 0.001, 0.01, 0.05]

results = []

for min_impurity_decrease in min_impurity_decrease_values:

    regressor = RandomForestRegressor(
        criterion='squared_error',
        max_features='sqrt',
        n_estimators=100,
        max_depth=8,
        min_samples_split=2,
        min_samples_leaf=1,
        max_leaf_nodes=None,
        min_impurity_decrease=min_impurity_decrease,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    results.append({
        'min_impurity_decrease': min_impurity_decrease,
        'R2': r_score
    })

results_df = pd.DataFrame(results).sort_values(
    by='R2', ascending=False
)

results_df

   min_impurity_decrease        R2
3                  0.050  0.885356
1                  0.001  0.885274
0                  0.000  0.885274
2                  0.010  0.885196

In [9]:
ccp_alpha_values = [0, 0.001, 0.01, 0.05]

results = []

for ccp_alpha in ccp_alpha_values:

    regressor = RandomForestRegressor(
        criterion='squared_error',
        max_features='sqrt',
        n_estimators=100,
        max_depth=8,
        min_samples_split=2,
        min_samples_leaf=1,
        max_leaf_nodes=None,
        min_impurity_decrease=0.05,
        ccp_alpha=ccp_alpha,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    results.append({
        'ccp_alpha': ccp_alpha,
        'R2': r_score
    })

results_df = pd.DataFrame(results).sort_values(
    by='R2', ascending=False
)

results_df

   ccp_alpha        R2
0      0.000  0.885356
1      0.001  0.885356
2      0.010  0.885356
3      0.050  0.885356

In [10]:
bootstrap_values = [True, False]

results = []

for bootstrap in bootstrap_values:

    regressor = RandomForestRegressor(
        criterion='squared_error',
        max_features='sqrt',
        n_estimators=100,
        max_depth=8,
        min_samples_split=2,
        min_samples_leaf=1,
        max_leaf_nodes=None,
        min_impurity_decrease=0.05,
        ccp_alpha=0,
        bootstrap=bootstrap,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    results.append({
        'bootstrap': bootstrap,
        'R2': r_score
    })

results_df = pd.DataFrame(results).sort_values(
    by='R2', ascending=False
)

results_df

   bootstrap        R2
0       True  0.885356
1      False  0.881135

In [11]:
regressor = RandomForestRegressor(
    criterion='squared_error',
    max_features='sqrt',
    n_estimators=100,
    max_depth=8,
    min_samples_split=2,
    min_samples_leaf=1,
    max_leaf_nodes=None,
    min_impurity_decrease=0.05,
    ccp_alpha=0,
    bootstrap=True,
    random_state=0
)

regressor.fit(X_train, y_train.values.ravel())

y_pred = regressor.predict(X_test)

r_score = r2_score(y_test, y_pred)

print("Final Random Forest R2 Score:", r_score)

Final Random Forest R2 Score: 0.8853564360347101